<?php

namespace ContainerGFn9P2x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_UxIcons_TwigIconRuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.ux_icons.twig_icon_runtime' shared service.
     *
     * @return \Symfony\UX\Icons\Twig\UXIconRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-icons/src/Twig/UXIconRuntime.php';

        return $container->privates['.ux_icons.twig_icon_runtime'] = new \Symfony\UX\Icons\Twig\UXIconRuntime(($container->privates['.ux_icons.icon_renderer'] ?? $container->load('get_UxIcons_IconRendererService')), false, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
