<?php

namespace ContainerGFn9P2x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlertService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Components\Alert' autowired service.
     *
     * @return \App\Twig\Components\Alert
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Twig/Components/Alert.php';

        $container->factories['service_container']['App\\Twig\\Components\\Alert'] = function ($container) {
            return new \App\Twig\Components\Alert();
        };

        return $container->factories['service_container']['App\\Twig\\Components\\Alert']($container);
    }
}
