version: "3.8"
services:

  db:
    image: mysql
    container_name: db_docker_symfony-co
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3308:3306"
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_symfony-co
    restart: always
    depends_on:
      - db
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
