<?php

namespace ContainerBFLbs0m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_UxIcons_TwigComponent_IconService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.ux_icons.twig_component.icon' service.
     *
     * @return \Symfony\UX\Icons\Twig\UXIconComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-icons/src/Twig/UXIconComponent.php';

        $container->factories['service_container']['.ux_icons.twig_component.icon'] = function ($container) {
            return new \Symfony\UX\Icons\Twig\UXIconComponent();
        };

        return $container->factories['service_container']['.ux_icons.twig_component.icon']($container);
    }
}
