<?php

namespace ContainerBFLbs0m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_UxIcons_IconFinderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.ux_icons.icon_finder' shared service.
     *
     * @return \Symfony\UX\Icons\Twig\IconFinder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-icons/src/Twig/IconFinder.php';

        $a = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->privates['.ux_icons.icon_finder'])) {
            return $container->privates['.ux_icons.icon_finder'];
        }

        return $container->privates['.ux_icons.icon_finder'] = new \Symfony\UX\Icons\Twig\IconFinder($a, (\dirname(__DIR__, 4).'/assets/icons'));
    }
}
