<?php

namespace ContainerBFLbs0m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_UxIcons_Command_LockService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.ux_icons.command.lock' shared service.
     *
     * @return \Symfony\UX\Icons\Command\LockIconsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-icons/src/Command/LockIconsCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-icons/src/IconRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-icons/src/Registry/LocalSvgIconRegistry.php';

        $container->privates['.ux_icons.command.lock'] = $instance = new \Symfony\UX\Icons\Command\LockIconsCommand(($container->privates['.ux_icons.iconify'] ?? $container->load('get_UxIcons_IconifyService')), ($container->privates['.ux_icons.local_svg_icon_registry'] ??= new \Symfony\UX\Icons\Registry\LocalSvgIconRegistry((\dirname(__DIR__, 4).'/assets/icons'), [])), ($container->privates['.ux_icons.icon_finder'] ?? $container->load('get_UxIcons_IconFinderService')));

        $instance->setName('ux:icons:lock');
        $instance->setDescription('Scan project and import icon(s) from iconify.design');

        return $instance;
    }
}
