<?php

namespace ContainerBFLbs0m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_TwigComponent_ComponentFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.twig_component.component_factory' shared service.
     *
     * @return \Symfony\UX\TwigComponent\ComponentFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-twig-component/src/ComponentFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-twig-component/src/ComponentTemplateFinderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-twig-component/src/ComponentTemplateFinder.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['ux.twig_component.component_factory'])) {
            return $container->privates['ux.twig_component.component_factory'];
        }

        return $container->privates['ux.twig_component.component_factory'] = new \Symfony\UX\TwigComponent\ComponentFactory(new \Symfony\UX\TwigComponent\ComponentTemplateFinder(($container->privates['twig.loader.native_filesystem'] ?? self::getTwig_Loader_NativeFilesystemService($container)), 'components/'), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Alert' => [false, 'App\\Twig\\Components\\Alert', 'getAlertService', true],
            'UX:Icon' => [false, '.ux_icons.twig_component.icon', 'get_UxIcons_TwigComponent_IconService', true],
        ], [
            'Alert' => '?',
            'UX:Icon' => '?',
        ]), ($container->privates['property_accessor'] ?? self::getPropertyAccessorService($container)), $a, ['Alert' => ['expose_public_props' => true, 'attributes_var' => 'attributes', 'key' => 'Alert', 'service_id' => 'App\\Twig\\Components\\Alert', 'class' => 'App\\Twig\\Components\\Alert', 'template' => 'components/Alert.html.twig'], 'UX:Icon' => ['key' => 'UX:Icon', 'service_id' => '.ux_icons.twig_component.icon', 'class' => 'Symfony\\UX\\Icons\\Twig\\UXIconComponent', 'template' => 'components/UX/Icon.html.twig']], ['App\\Twig\\Components\\Alert' => 'Alert', 'Symfony\\UX\\Icons\\Twig\\UXIconComponent' => 'UX:Icon']);
    }
}
