<?php

namespace ContainerBFLbs0m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_LiveComponent_LiveControllerAttributesCreatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.live_component.live_controller_attributes_creator' shared service.
     *
     * @return \Symfony\UX\LiveComponent\Util\LiveControllerAttributesCreator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/Util/LiveControllerAttributesCreator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/LiveResponder.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/Twig/DeterministicTwigIdCalculator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/Util/FingerprintCalculator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/Twig/TemplateMap.php';

        return $container->privates['ux.live_component.live_controller_attributes_creator'] = new \Symfony\UX\LiveComponent\Util\LiveControllerAttributesCreator(($container->privates['ux.live_component.metadata_factory'] ?? $container->load('getUx_LiveComponent_MetadataFactoryService')), ($container->privates['ux.live_component.component_hydrator'] ?? $container->load('getUx_LiveComponent_ComponentHydratorService')), ($container->privates['ux.live_component.attribute_helper_factory'] ?? $container->load('getUx_LiveComponent_AttributeHelperFactoryService')), ($container->privates['ux.live_component.deterministic_id_calculator'] ??= new \Symfony\UX\LiveComponent\Twig\DeterministicTwigIdCalculator()), ($container->privates['ux.live_component.fingerprint_calculator'] ??= new \Symfony\UX\LiveComponent\Util\FingerprintCalculator($container->getEnv('APP_SECRET'))), ($container->services['router'] ?? self::getRouterService($container)), new \Symfony\UX\LiveComponent\LiveResponder(), ($container->privates['security.csrf.token_manager'] ?? self::getSecurity_Csrf_TokenManagerService($container)), ($container->privates['ux.live_component.twig.template_mapper'] ??= new \Symfony\UX\LiveComponent\Twig\TemplateMap(($container->targetDir.''.'/live_components_twig_templates.map'))));
    }
}
