<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGFn9P2x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGFn9P2x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGFn9P2x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGFn9P2x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGFn9P2x\App_KernelDevDebugContainer([
    'container.build_hash' => 'GFn9P2x',
    'container.build_id' => '1b3345de',
    'container.build_time' => 1729159189,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGFn9P2x');
